### ISSUE TITLE
Preceding "L" character breaks logger json parsing 

### ISSUE THREAD

**Issue by ihs-nick** [nuclio/nuclio-sdk-py#31]
https://github.com/nuclio/nuclio-sdk-py/blob/59687c12bcdac8b0b79eda1d2b1a1f53435fcb57/nuclio_sdk/logger.py#L34

This causes a breakage in parsing of the json. Notice the "Replacing logger output" message below.

![Screen Shot 2021-06-25 at 2 37 51 PM](https://user-images.githubusercontent.com/70656471/123484555-c7a9ce00-d5c5-11eb-88fc-5c03f532c784.png)

**Comment by liranbg** [comment]
Hey @ihs-nick,

Thanks for the PR contribution, Ive merged it today. I wanted give some information w.r.t issue,
The idea is that the user function communicate back to the processor, using a prefix character about the message it sends. the `l` you see here, is of course a bug on which you alert, and happen because the character is being added _before_ the logger handler changes from `stdout` to `socket`.

The resolution, as suggested by https://github.com/nuclio/nuclio/pull/2238 is to append the `l` only _after_ the logger handler changes.

I will close this issue once I finish up with above PR & release a new (minor-bumped) nuclio-sdk-py version.

I wanted to know, btw, which logs processor are you using on the attached picture?

**Comment by ihs-nick** [comment]
Hi @liranbg,

Thanks for the details on how this works and the fast work to resolve it. I look forward to the PR being merged. 

I'm using a Kibana discover dashboard to visualize the logs from all nuclio functions and have an easy filter to get only a single function or project. I'm happy to share how I'm doing this if it would be helpful or of interest!

**Comment by liranbg** [comment]
Hey @ihs-nick - Note that this issue is no longer part of Nuclio 1.6.x (currently under development) and soon will be also fixed on Nuclio 1.5.x

Feel free to share with us the way to set up Kibana discover dashboard with Nuclio. I am sure many Nuclioers would be happy to learn how they can collect and visualize Nuclio logs.

I will close this issue once the fix, part of 1.5.x, is released

**Comment by liranbg** [comment]
done and resolved on nuclio >= 1.7.x
